#!/usr/bin/env node
var fs = require('fs')
  , path = require('path')
  , paths = require('../config/paths')
  , zlib = require('zlib');

/*
  Cron job that runs daily to backup the database as a tarred json document.
  TODO: put the backups to S3.
*/

var backupFolder = path.join(paths.persistent, 'backups');

function getBackupPath(backupDate) {
  var dateString = backupDate.getFullYear() + '-' + (1 + backupDate.getMonth()) + '-' + backupDate.getDate();
  return path.join(backupFolder, dateString + '-' + path.basename(paths.db) + '.gz');
}

if (!fs.existsSync(backupFolder)) {
  console.log('Creating backups folder at ' + backupFolder);
  fs.mkdirSync(backupFolder);
}

console.log('backing up db at ' + paths.db);
var today = new Date();
var gzip = zlib.createGzip();
var outputFile = getBackupPath(today);
var inp = fs.createReadStream(paths.db, { encoding: 'utf8', flags: 'r' });
var out = fs.createWriteStream(outputFile, { encoding: 'utf8', flags: 'w' });

inp.pipe(gzip).pipe(out);
console.log('created backup at ' + outputFile);

var fiveDaysOld = getBackupPath(today.setDate(today.getDate()));
if (fs.existsSync(fiveDaysOld)) {
  console.log('Deleting old database backup at ' + fiveDaysOld);
  fs.unlinkSync(fiveDaysOld);
}
