#!/usr/bin/env bash

# This is a very light deployment script, a fully featured one should be written in the future
if [ "$1" == "-h" ]; then
    echo "Run this file with the absolute path to the yodel ec2 pem file. Ex: ./deploy.sh /path/to/pem/file/pemFile.pem"
    exit 0
fi

if [ $# -eq 0 ]; then
    echo "No arguments provided. Please provide a path to a pem file. e.g. './deploy.sh /path/to/pem/file/pemFile.pem'"
    exit 1
fi

command -v node >/dev/null 2>&1 || n latest
command -v bower >/dev/null 2>&1 || npm install -g bower
command -v gulp >/dev/null 2>&1 || npm install -g gulp

HOSTNAME=ubuntu@52.26.65.193
DIR=/home/ubuntu
FOLDER=yodel

DEPLOY_BOT_NAME="deploy-bot"
DEPLOY_BOT_EMOJI=":soccer:"
# TODO: Don't check in credentials; read this from file
SLACK_API_TOKEN="xoxp-11333240867-11333423428-13379590359-8b9d72ad81"

function notifySlackAndConsole {
  echo $1
  curl -X POST --data-urlencode 'payload={"text": "'"$1"'", "channel": "#ops", "username": "'"$DEPLOY_BOT_NAME"'", "icon_emoji": "'"$DEPLOY_BOT_EMOJI"'"}' https://hooks.slack.com/services/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
}

CURRENT_GIT_SHA=$(git rev-parse HEAD)
PAST_GIT_SHA=`cat ~/workplace/yodel-persistent/deploy-log`
notifySlackAndConsole `git log ${PAST_GIT_SHA}..${CURRENT_GIT_SHA}`
echo CURRENT_GIT_SHA > ~/workplace/yodel-persistent/deploy-log

notifySlackAndConsole "compiling local instance for deployment"
gulp clean-all
gulp compile-prod

notifySlackAndConsole "copying aws credentials"
scp -r -i {$1} ~/.aws ${HOSTNAME}:${DIR}

# TODO: Run the tests and fail the deploy if they don't pass.
notifySlackAndConsole "ssh-ing to remote host to remove existing yodel app"

ssh -i ${1} ${HOSTNAME} <<ENDSSH
    echo "Installing nodejs"
    sudo apt-get install nodejs

    echo "Installing latest version of node"
    sudo npm install -g n
    sudo n latest

    echo "Installing build tool chain"
    sudo apt-get install git # reqired by bower
    sudo npm install -g bower
    sudo npm install -g forever
    sudo apt-get install build-essential # TODO: this isn't installed correctly
    sudo apt-get install nginx
    sudo npm install -g node-gyp

    echo "deleting existing yodel app"
    cd ${DIR}
    rm -rf ${FOLDER}
    mkdir -p ./yodel-persistent/logs
ENDSSH

notifySlackAndConsole "Tarring source folders"
tar czf ../app.tar.gz bower.json package.json build config public templates README.md .bowerrc

notifySlackAndConsole "SCPing app tarball"
scp -i ${1} ../app.tar.gz  ${HOSTNAME}:${DIR}

notifySlackAndConsole "ssh-ing to remote host to install and start yodel"
ssh -i ${1} ${HOSTNAME} <<ENDSSH
    echo "sshed into remote host"
    cd ${DIR}
    mkdir ${FOLDER}

    echo "Untarring source directory on server"
    tar -xvf app.tar.gz --directory ${FOLDER}
    rm app.tar.gz
    cd ${FOLDER}

    echo "Installing dependencies on remote server; please be patient"
    npm install --production
    bower install --production

    echo "Configuring nginx"
    sudo cp ./config/nginx.conf /etc/nginx/nginx.conf
    service nginx start

    echo "Starting server"
    forever restart ./build/server.js
ENDSSH

notifySlackAndConsole "Deployed Yodel!"

echo "Removing local tarball"
rm ../app.tar.gz
