#!/usr/bin/env node
var argv = require('minimist')(process.argv.slice(2));
var aws = require('aws-sdk');
var config = require('../build/config');
var db = require('../build/util/db');
var logger = require('../build/logger');
var testData = require('../config/test-data');

if (argv.h || argv.help) {
  [
    'This script load test data in a DynamoDB instance.  We recommend you pipe the logs through bunyan using the short format.',
    'Options:',
    '  -h -help Show this help message.'
  ].forEach((line) => console.log(line));
}

aws.config.update({
  region: config.aws.region,
  endpoint: config.aws.endpoint
});

logger.info('inserting test data.');
testData.contacts.forEach(function(contact) {
  db.createContact(contact);
});

testData.users.forEach(function(user) {
  db.addUser(user).then((res) => {
    testData.projects.forEach((project) => {
      if (project.username === user.username) {
        project.userId = res.userId;
        db.addProject(project);
      }
    });
  });
});

db.addDisciplines(testData.disciplines);

testData.events.forEach(function(testEvent) {
  db.addEvent(testEvent);
});

// testData.portfolios.forEach(function (portfolio) {
//   portfolio.userId = createdUsers[Math.floor(Math.random() * createdUsers.length)];
//   db.addPortfolio(portfolio);
// });
